version: '3'

services:

  web:
    container_name: kobaco
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - DB_URL=${DATASOURCE_URL_LOCAL}
      - DB_USERNAME=${DATASOURCE_USERNAME}
      - DB_PASSWORD=${DATASOURCE_PASSWORD}
